Thème finalisé (première ébauche)
cr-crme/crcrme_material_theme pull request #3
Opened 2022-06-28 21:46 UTC by Guibi1

À évaluer et à modifier selon le feedback que l'on reçois.

2022-06-29 13:04 UTC, pariterre requested changes
If you can add some description (and low resolution images?) to the ReadMe, that will be nice. I suggest though to add the images once the theme is accepted so we don't bloat the repository with useless images

2022-06-29 13:04 UTC, pariterre commented on lib/screens/input_showcase.dart
> +  bool switchh = false;
I feel these should be private (_dropdownValue)

2022-06-29 13:04 UTC, pariterre commented on lib/screens/input_showcase.dart
> +  bool? radio = false;
I feel these should be actual `bool`. I know RadioListTile returns a `bool?`, but I am not sure how it can be... If it is not possible for `_isChecked` and `_radio` to be null, please use `bool` and use the bang operator (!) when setting them (`_radio = v!`)

2022-06-29 13:04 UTC, pariterre commented on lib/screens/home.dart
> +  int currentStep = 0;
Same comments as input_showcase file

2022-06-29 13:04 UTC, pariterre commented
Good job so far! :D

2022-06-29 15:04 UTC, Guibi1 commented on lib/screens/input_showcase.dart
> +  bool switchh = false;
Done!

2022-06-29 15:06 UTC, Guibi1 commented
* I fixed the variables
* I updated the readme with _screenshots_ and _usage_
* I prepared the project to be published to [pub.dev](https://pub.dev)

2022-06-29 15:43 UTC, pariterre requested changes

2022-06-29 15:43 UTC, pariterre commented on .pubignore
> +windows/
Compilation folder SHOULD be included

2022-06-29 15:43 UTC, pariterre commented on lib/screens/home.dart
> +      body: Padding(
There should be a SingleScroll.. somewhere because it overflows on my emulator

2022-06-29 15:44 UTC, Guibi1 commented on .pubignore
> +windows/
Even though we will be using the package only for the theme? The compilation folders are for the demo app...

2022-06-30 13:29 UTC, pariterre commented on .pubignore
> +windows/
Based on the documentation (https://dart.dev/tools/pub/publishing): 
```
What files are published?

All files under the package root directory are included in the published package, with the following exceptions:

    Any hidden files or directories—that is, files with names that begin with dot (.)
    Any directories with the name packages
    Files and directories ignored by a .pubignore or .gitignore file

If you want different ignore rules for git and dart pub publish, then overrule the .gitignore file in a given directory by creating a .pubignore file. (If a directory contains both a .pubignore file and a .gitignore file, then dart pub publish doesn’t read that directory’s .gitignore file.) The format of .pubignore files is the same as the [.gitignore file format](https://git-scm.com/docs/gitignore#_pattern_format).

To avoid publishing unwanted files, follow these practices:

    Either delete any files that you don’t want to include, or add them to a .pubignore or .gitignore file.
    When uploading your package, carefully examine the list of files that dart pub publish says it’s going to publish. Cancel the upload if any undesired files appear in that list.
```

Most importantly, .gitignore already ignore the actual compiled file. The files which are included are the configuration files for the app (for instance, on a normal settings you should not ignore these folder). But I could not find anywhere if we should ignore these configuration files when publishing a library. That said, in this very documentation, they refer to a thread in Stack Overflow which starts by: `I work on dart pub, and the short answer is: Most developers probably won't need to use .pubignore` which makes me feel that these folder should indeed be included... Can you confirm that we should ignore them?

2022-06-30 13:48 UTC, pariterre requested changes
Excellent! I just added some comment (2 I think) and I think we'll be ready to merge afterwards :)

> Reviewed 6 of 11 files at r1, 15 of 16 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cr-crme/crcrme_flutter_template/3#-:-N5orZXh7PPOiPiJ6pCj:bk4yx0w)* status: all files reviewed, 6 unresolved discussions (waiting on @Guibi1)

___
*[`lib/main.dart` line 3 at r3](https://reviewable.io/reviews/cr-crme/crcrme_flutter_template/3#-N5op0aj1FOGmdU1_Aqj:-N5op0aj1FOGmdU1_Aqk:b4v43ug) ([raw file](https://github.com/cr-crme/crcrme_flutter_template/blob/37e6374812c70285d7edc7912c82db6c260eff55/lib/main.dart#L3)):*
> ```Dart
> import 'package:crcrme_material_theme/screens/home.dart';
> import 'package:crcrme_material_theme/screens/button_showcase.dart';
> import 'package:crcrme_material_theme/screens/input_showcase.dart';
> ```

Even though visual studio imports local files as `import 'package:...';`, dart actually recommends to import in a relative manner (https://dart.dev/tools/linter-rules#prefer_relative_imports)  `import 'home.dart';` for instance



_Code quote:_
```Dart
import 'package:crcrme_material_theme/screens/home.dart';
import 'package:crcrme_material_theme/screens/button_showcase.dart';
import 'package:crcrme_material_theme/screens/input_showcase.dart';
import 'package:crcrme_material_theme/screens/dialog_showcase.dart';
```
___
*[`lib/main.dart` line 5 at r3](https://reviewable.io/reviews/cr-crme/crcrme_flutter_template/3#-N5opcZR9_TsGSEbNIKz:-N5opcZR9_TsGSEbNIL-:b7mmb3x) ([raw file](https://github.com/cr-crme/crcrme_flutter_template/blob/37e6374812c70285d7edc7912c82db6c260eff55/lib/main.dart#L5)):*
> ```Dart
> import 'package:crcrme_material_theme/screens/input_showcase.dart';
> import 'package:crcrme_material_theme/screens/dialog_showcase.dart';
> import 'package:crcrme_material_theme/crcrme_material_theme.dart';
> ```

Since we are creating a package, I would keed this one as is though. That said, package imports should appear first (before local files)
___
*[`lib/main.dart` line 19 at r3](https://reviewable.io/reviews/cr-crme/crcrme_flutter_template/3#-N5ooXmH6LKJsr-MuGSX:-N5ooXmH6LKJsr-MuGSY:b-b29kt8) ([raw file](https://github.com/cr-crme/crcrme_flutter_template/blob/37e6374812c70285d7edc7912c82db6c260eff55/lib/main.dart#L19)):*
> ```Dart
>     return MaterialApp(
>       title: 'CR-CRME theme',
>       theme: crcrmeMaterialTheme,
> ```

This may be slightly picky but I was thinking, should CrcrmeMaterialTheme be an actual widget which extends ThemeData instead of get? I feel that it is weird to call a function here while the vanilla way to do things in Flutter are creating a `const Widget()` whenever possible?
___
*[`lib/screens/home.dart` line 3 at r3](https://reviewable.io/reviews/cr-crme/crcrme_flutter_template/3#-N5optpiBtAx5CYhKnxx:-N5optpiBtAx5CYhKnxy:b-nrbnbf) ([raw file](https://github.com/cr-crme/crcrme_flutter_template/blob/37e6374812c70285d7edc7912c82db6c260eff55/lib/screens/home.dart#L3)):*
> ```Dart
> import 'package:crcrme_material_theme/screens/button_showcase.dart';
> import 'package:crcrme_material_theme/screens/input_showcase.dart';
> import 'package:crcrme_material_theme/screens/dialog_showcase.dart';
> ```

Reorganise and push material.dart first (separated with a white space)



_Code quote:_
```Dart
import 'package:crcrme_material_theme/screens/button_showcase.dart';
import 'package:crcrme_material_theme/screens/input_showcase.dart';
import 'package:crcrme_material_theme/screens/dialog_showcase.dart';
```


<!-- Sent from Reviewable.io -->

2022-06-30 15:07 UTC, Guibi1 reviewed
> *[Reviewable](https://reviewable.io/reviews/cr-crme/crcrme_flutter_template/3)* status: 20 of 22 files reviewed, 6 unresolved discussions (waiting on @pariterre)

___
*[`.pubignore` line 8 at r2](https://reviewable.io/reviews/cr-crme/crcrme_flutter_template/3#-N5oo7LKRwbK9PpEi-dU-r2-8:-N5p75Z_EmLXh1pTppV9:b-g3y95a) ([raw file](https://github.com/cr-crme/crcrme_flutter_template/blob/c20b2acb8aae2112dae215dcd7801b61ca216fce/.pubignore#L8)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Based on the documentation (https://dart.dev/tools/pub/publishing): 
```
What files are published?

All files under the package root directory are included in the published package, with the following exceptions:

    Any hidden files or directories—that is, files with names that begin with dot (.)
    Any directories with the name packages
    Files and directories ignored by a .pubignore or .gitignore file

If you want different ignore rules for git and dart pub publish, then overrule the .gitignore file in a given directory by creating a .pubignore file. (If a directory contains both a .pubignore file and a .gitignore file, then dart pub publish doesn’t read that directory’s .gitignore file.) The format of .pubignore files is the same as the [.gitignore file format](https://git-scm.com/docs/gitignore#_pattern_format).

To avoid publishing unwanted files, follow these practices:

    Either delete any files that you don’t want to include, or add them to a .pubignore or .gitignore file.
    When uploading your package, carefully examine the list of files that dart pub publish says it’s going to publish. Cancel the upload if any undesired files appear in that list.
```

Most importantly, .gitignore already ignore the actual compiled file. The files which are included are the configuration files for the app (for instance, on a normal settings you should not ignore these folder). But I could not find anywhere if we should ignore these configuration files when publishing a library. That said, in this very documentation, they refer to a thread in Stack Overflow which starts by: `I work on dart pub, and the short answer is: Most developers probably won't need to use .pubignore` (https://stackoverflow.com/questions/69760021/what-should-be-ignored-in-darts-pubignore/69767697#69767697) which makes me feel that these folder should indeed be included... Can you confirm that we should ignore them?
</blockquote></details>

Yes I can confirm. The source code of the packages that I looked at on pub.dev did not have any build folders.
___
*[`lib/main.dart` line 3 at r3](https://reviewable.io/reviews/cr-crme/crcrme_flutter_template/3#-N5op0aj1FOGmdU1_Aqj:-N5p7r8oBFuu0GgTrlhF:b-896fix) ([raw file](https://github.com/cr-crme/crcrme_flutter_template/blob/37e6374812c70285d7edc7912c82db6c260eff55/lib/main.dart#L3)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Even though visual studio imports local files as `import 'package:...';`, dart actually recommends to import in a relative manner (https://dart.dev/tools/linter-rules#prefer_relative_imports)  `import 'home.dart';` for instance
</blockquote></details>

Done.
___
*[`lib/main.dart` line 5 at r3](https://reviewable.io/reviews/cr-crme/crcrme_flutter_template/3#-N5opcZR9_TsGSEbNIKz:-N5p7rgj5Lu4dmqtqMdY:b-896fix) ([raw file](https://github.com/cr-crme/crcrme_flutter_template/blob/37e6374812c70285d7edc7912c82db6c260eff55/lib/main.dart#L5)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Since we are creating a package, I would keed this one as is though. That said, package imports should appear first (before local files)
</blockquote></details>

Done.
___
*[`lib/main.dart` line 19 at r3](https://reviewable.io/reviews/cr-crme/crcrme_flutter_template/3#-N5ooXmH6LKJsr-MuGSX:-N5p7vmt9e7aS7hkbKFw:b-48vmf3) ([raw file](https://github.com/cr-crme/crcrme_flutter_template/blob/37e6374812c70285d7edc7912c82db6c260eff55/lib/main.dart#L19)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

This may be slightly picky but I was thinking, should CrcrmeMaterialTheme be an actual widget which extends ThemeData instead of get? I feel that it is weird to call a function here while the vanilla way to do things in Flutter are creating a `const Widget()` whenever possible?
</blockquote></details>

No. To use a widget here we would need to "redo" a MaterialApp widget and override the theme attribute. ThemeData is not a widget so there is no need us to use one...
___
*[`lib/screens/home.dart` line 42 at r2](https://reviewable.io/reviews/cr-crme/crcrme_flutter_template/3#-N5oo7LKRwbK9PpEi-dK-r2-42:-N5p8HRmDYtC-xk_xTDg:b-896fix) ([raw file](https://github.com/cr-crme/crcrme_flutter_template/blob/c20b2acb8aae2112dae215dcd7801b61ca216fce/lib/screens/home.dart#L42)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

There should be a SingleScroll.. somewhere because it overflows on my emulator
</blockquote></details>

Done.
___
*[`lib/screens/home.dart` line 3 at r3](https://reviewable.io/reviews/cr-crme/crcrme_flutter_template/3#-N5optpiBtAx5CYhKnxx:-N5p8ECMEC58xKSZtfWW:b-896fix) ([raw file](https://github.com/cr-crme/crcrme_flutter_template/blob/37e6374812c70285d7edc7912c82db6c260eff55/lib/screens/home.dart#L3)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Reorganise and push material.dart first (separated with a white space)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-06-30 15:40 UTC, pariterre approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cr-crme/crcrme_flutter_template/3#-:-N5pGElyAkRtdjM50EW9:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @Guibi1 and @pariterre)

___
*[`lib/main.dart` line 19 at r3](https://reviewable.io/reviews/cr-crme/crcrme_flutter_template/3#-N5ooXmH6LKJsr-MuGSX:-N5pG5XDAo8BL2UfCUfZ:btytmnq) ([raw file](https://github.com/cr-crme/crcrme_flutter_template/blob/37e6374812c70285d7edc7912c82db6c260eff55/lib/main.dart#L19)):*
<details><summary><i>Previously, Guibi1 (Laurent Stéphenne) wrote…</i></summary><blockquote>

No. To use a widget here we would need to "redo" a MaterialApp widget and override the theme attribute. ThemeData is not a widget so there is no need us to use one...
</blockquote></details>

I see, we can fix that later if it ever becomes relevant


<!-- Sent from Reviewable.io -->

2022-06-30 15:44 UTC, pariterre requested changes
> *[Reviewable](https://reviewable.io/reviews/cr-crme/crcrme_flutter_template/3)* status: all files reviewed, 2 unresolved discussions (waiting on @Guibi1)

___
*[`.pubignore` line 8 at r2](https://reviewable.io/reviews/cr-crme/crcrme_flutter_template/3#-N5oo7LKRwbK9PpEi-dU-r2-8:-N5pGjIe8eMJUfe6hKKa:beec22l) ([raw file](https://github.com/cr-crme/crcrme_flutter_template/blob/c20b2acb8aae2112dae215dcd7801b61ca216fce/.pubignore#L8)):*
<details><summary><i>Previously, Guibi1 (Laurent Stéphenne) wrote…</i></summary><blockquote>

Yes I can confirm. The source code of the packages that I looked at on pub.dev did not have any build folders.
</blockquote></details>

I had a look at the "provider" package (https://github.com/rrousselGit/provider) there is indeed no build folder. The main reason is that "example" is not in a main.dart file in lib, but in an example folder. 
I think it would make sense to mimic that structure!


<!-- Sent from Reviewable.io -->

2022-06-30 15:54 UTC, Guibi1 reviewed
> *[Reviewable](https://reviewable.io/reviews/cr-crme/crcrme_flutter_template/3)* status: 17 of 22 files reviewed, 2 unresolved discussions (waiting on @pariterre)

___
*[`.pubignore` line 8 at r2](https://reviewable.io/reviews/cr-crme/crcrme_flutter_template/3#-N5oo7LKRwbK9PpEi-dU-r2-8:-N5pJFVd7GUa55JJCGsH:b-896fix) ([raw file](https://github.com/cr-crme/crcrme_flutter_template/blob/c20b2acb8aae2112dae215dcd7801b61ca216fce/.pubignore#L8)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

I had a look at the "provider" package (https://github.com/rrousselGit/provider) there is indeed no build folder. The main reason is that "example" is not in a main.dart file in lib, but in an example folder. 
I think it would make sense to mimic that structure!
</blockquote></details>

Done.
___
*[`lib/main.dart` line 19 at r3](https://reviewable.io/reviews/cr-crme/crcrme_flutter_template/3#-N5ooXmH6LKJsr-MuGSX:-N5pIpr25tHd4z4nOnXT:b-j6u9bs) ([raw file](https://github.com/cr-crme/crcrme_flutter_template/blob/37e6374812c70285d7edc7912c82db6c260eff55/lib/main.dart#L19)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

I see, we can fix that later if it ever becomes relevant
</blockquote></details>

Perfect


<!-- Sent from Reviewable.io -->

2022-06-30 18:44 UTC, pariterre approved these changes
> Reviewed 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cr-crme/crcrme_flutter_template/3)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Guibi1)



<!-- Sent from Reviewable.io -->

2022-06-30 18:44 UTC, merged